### ISSUE TITLE
If doesn't exist, provide a way to know the status of the execution of the test in .TearDownWith()

### ISSUE THREAD

**Issue by isaldarriaga** [TestStack/TestStack.BDDfy#214]
I couldn't find a way to know the status of execution of an Example at runtime. The BDDfy extensions seems to hide that information, but not sure.

The workaround has been to always pass a status of PASSED to the callback function set in .TearDownWith(), and a status of FAILED in a try/catch block inside each step of the test, everytime the step fails.

The problem: since the .TearDownWith() is called all the times, it's running 2 times per failed example (in the try/catch block and when the teardown's callback is invoked). So to avoid extra processing, i needed to implement a flag to determine the teardown of the example has been already done or not before cleaning up data, etc..

Let me know if there's a way to know the status of execution of the test by using the framework.

tks,

IS.

**Comment by MehdiK** [comment]
Hi @isaldarriaga,

You could use `LazyBDDfy`. It is what BDDfy uses [internally](https://github.com/TestStack/TestStack.BDDfy/blob/master/src/TestStack.BDDfy/BDDfyExtensions.cs#L17). You can see some unit tests [here](https://github.com/TestStack/TestStack.BDDfy/blob/6e797fb9e000dcb7d53a3d8a4e26abdfc8bd3a06/src/TestStack.BDDfy.Tests/Disposer/DisposingScenarios.cs#L54). 

Closing the issue now. Please reopen if this doesn't answer your question.

**Comment by isaldarriaga** [comment]
Hi @MehdiK,

Can you please point me out to the documentation of LazyBDDfy. I tried to use that extension before without luck. I always get this in the inspector:

this.LazyBDDfy()
{TestStack.BDDfy.Engine}
    Story: null

If there's no documentation about it, let me know how to use it in the .TearDownWith callback to extract the example's Result value.

Thanks.

**Comment by MehdiK** [comment]
There are no written documentations for it; but it's all documented in the code.

As you can see in the [unit tests](https://github.com/TestStack/TestStack.BDDfy/blob/6e797fb9e000dcb7d53a3d8a4e26abdfc8bd3a06/src/TestStack.BDDfy.Tests/Disposer/DisposingScenarios.cs#L59), `LazyBDDfy` does NOT run by itself. It's, errrrm, lazy! You would have to call `Run` on it. Also need to wrap it in try-catch so it doesn't stop your test run. The unit test code is almost exactly what you need.

HTH
