### ISSUE TITLE
Textcontext.current.result equivalent 

### ISSUE THREAD

**Issue by brianjmitchell** [TestStack/TestStack.BDDfy#273]
I was wondering if there was a way to get the status of a test after its executed via BDDfy?

**Comment by mwhelan** [comment]
Hi @brianjmitchell . Off the top of my head, I don't think there is an equivalent exactly. You might take a look at StoryCache.Stories. The Story and each of its Scenarios have a result property which will tell you if it passed or failed, etc.

What is it you are trying to do? Is it NUnit you are using?

**Comment by brianjmitchell** [comment]
Hi @mwhelan I am trying to build a feature in which on failure a screenshot is taken, I am currently using Xunit. 
We are moving from a framework using Specflow and Nunit to BDDfy and Xunit.

The StoryCache certainly looks interesting, I will take a look 👍

**Comment by mwhelan** [comment]
OK. You could possibly create a custom processor then, similar to the [ExceptionProcessor](https://github.com/TestStack/TestStack.BDDfy/blob/master/src/TestStack.BDDfy/Processors/ExceptionProcessor.cs) in BDDfy.

```
    public class ErrorProcessor : IProcessor
    {
        public ProcessType ProcessType => ProcessType.ProcessExceptions;

        public void Process(Story story)
        {
            if (story.Result == Result.Failed)
            {
                // Take screenshot
            }
        }
    }
```

the add it into the pipeline before any tests run in xUnit:

```
Configurator.Processors.Add(() => new ErrorProcessor());
```

[This](http://www.michael-whelan.net/bddfy-architecture-overview/) is what is going on....

Haven't run this but hopefully it works. Let me know how you get on.

**Comment by brianjmitchell** [comment]
@mwhelan I am having a bit of trouble implementing this.

I have a setup which starts the web driver etc, is this the best place for this? 

Am I then supposed to call the method in dispose so it runs for every scenario?

It seems to go into the class when tearing down but skips the process method

**Comment by mwhelan** [comment]
You want to call Configurator.Processors.Add(() => new ErrorProcessor()); before any of your tests run. In NUnit, that would have been the [OneTimeSetup] method in a [SetUpFixture] class. Then hopefully the ErrorProcessor will run every time there is an error and take the screenshot.

**Comment by brianjmitchell** [comment]
Hmmm strange, I have placed it into the constructor of my WebdriverSetup (Which is my one time setup) and it's not being used.

In Xunit, i believe to be the equivalent as a [OneTimeSetup] binding

**Comment by brianjmitchell** [comment]
Although it may be due to another error I am having. 

I have an issue where when I run a test individually it runs fine. but when running a whole feature file which contains multiple scenarios the first tests pass and the rest fail. I feel this is due to the framework not closing the driver and creating a new one before each scenario.

It seems to roll from one scenario to the next without running the setup.

**Comment by mwhelan** [comment]
I haven't used xUnit for awhile, but I think you might need a CollectionFixture to achieve the same as NUnit where it runs once before all the tests. Alternatively, you could use a static constructor on one of your setup classes, perhaps the WebdriverSetup. I tend to just spin up WebDriver before all my tests and then dispose of it after they've all run. It tends to be much better performing. So, probably you want to add the Error Processor and WebDriver setup in the same place.

**Comment by brianjmitchell** [comment]
I have created an assembly fixture in which I have called the error processer 

```c#
using TestStack.BDDfy.Annotations;
using TestStack.BDDfy.Configuration;
using TestStack.BDDfy.Reporters.Html;
using Xunit.Abstractions;
using Xunit.Sdk;

[assembly: Xunit.TestFramework("Brian.Mitchell.Tests.Core.BDDfy.AssemblySetupFixture", "HGEM.DynamicSurvey.Tests")]

namespace Brian.Mitchell.Tests.Core.BDDfy
{
    [UsedImplicitly]
    public class AssemblySetupFixture : XunitTestFramework
    {
        public AssemblySetupFixture(IMessageSink messageSink)
            : base(messageSink)
        {
            Configurator.Processors.Add(() => new ErrorProcessor());
            Configurator.BatchProcessors.HtmlReport.Disable();
            Configurator.BatchProcessors.Add(new HtmlReporter(new HgemResultsApiHtmlReportConfig()));
        }
    }

    public class HgemResultsApiHtmlReportConfig : DefaultHtmlReportConfiguration
    {
        public override string ReportHeader => "HGEM";
    }
}


```
I know this is working due the html report now states HGEM, i also throw an exception in one of my steps to force it to fail

My ErrorProcessor looks like this

```c#
    public class ErrorProcessor : IProcessor
    {
        public ProcessType ProcessType => ProcessType.ProcessExceptions;

        public void Process(Story story)
        {
            if (story.Result == Result.Failed)
            {
                Console.WriteLine("The test has failed");
            }
        }
    }
}
```

When debugging we can see it hitting the getter for ProcessType but never calls Process

**Comment by mwhelan** [comment]
Try changing the ProcessType. Report and AfterReport work for me in this NUnit example:

```
    [SetUpFixture]
    public class AssemblyFixture
    {
        [OneTimeSetUp]
        public void RunBeforeAnyTests()
        {
            Configurator.Processors.Add(() => new ErrorProcessor());
        }
    }
    public class Fixture
    {
        public void When_I_throw_error()
        {
            throw new Exception();
        }

        [Test]
        public void Test1()
        {
            this.BDDfy();
        }
    }

    public class ErrorProcessor : IProcessor
    {
        public ProcessType ProcessType => ProcessType.AfterReport;

        public void Process(Story story)
        {
            if (story.Result == Result.Failed)
            {
                // Take screenshot
            }
        }
    }
```

**Comment by brianjmitchell** [comment]
Hi, @mwhelan Thanks for all your help!!! we have managed to get this working now.

switching the processor type seemed to do the trick

**Comment by mwhelan** [comment]
Excellent, I'm glad we got there in the end. I hope the rest of the move from SpecFlow goes well.
